// languageMappings.js

const languageMappings = {
  en: {
    homePath: "/en",
    homeText: "Welcome",
    specsPath: "/en/systemspecs",
    specsText: "System Requirements",
    instPath: "/en/installation",
    instText: "Installation",
    gcPath: "/en/gettingconnected",
    gcText: "Getting Connected",
    wwsPath: "/en/workingwithsessions",
    wwsText: "Working within a Session",
    dashPath: "/en/dashboard",
    dashText: "The Rim Management Dashboard",
    faqPath: "/en/faq",
    faqText: "Frequently Asked Questions",
    planPath: "/en/plans",
    planText: "Plans and Purchasing",
    clPath: "/en/changelog",
    clText: "Change Log"
  },
  es: {
    homePath: "/es",
    homeText: "Bienvenido",
    specsPath: "/es/systemspecs",
    specsText: "Requisitos del sistema",
    instPath: "/es/installation",
    instText: "Instalación",
    gcPath: "/es/gettingconnected",
    gcText: "Conectarse",
    wwsPath: "/es/workingwithsessions",
    wwsText: "Trabajar en una sesión",
    dashPath: "/es/dashboard",
    dashText: "El cuadro de mandos de la gestión de llantas",
    faqPath: "/es/faq",
    faqText: "Preguntas frecuentes",
    planPath: "/es/plans",
    planText: "Planes y compras",
    clPath: "/es/changelog",
    clText: "Registro de cambios"    
  },
  fr: {
    homePath: "/fr",
    homeText: "Bienvenue",
    specsPath: "/fr/systemspecs",
    specsText: "Configuration requise",
    instPath: "/fr/installation",
    instText: "Installation",
    gcPath: "/fr/gettingconnected",
    gcText: "Se connecter",
    wwsPath: "/fr/workingwithsessions",
    wwsText: "Travailler au sein d'une session",
    dashPath: "/fr/dashboard",
    dashText: "Le tableau de bord de la gestion des rives",
    faqPath: "/fr/faq",
    faqText: "Questions fréquemment posées",
    planPath: "/fr/plans",
    planText: "Plans et achats",
    clPath: "/fr/changelog",
    clText: "Journal des modifications"
  },
  it: {
    homePath: "/it",
    homeText: "Benvenuti",
    specsPath: "/it/systemspecs",
    specsText: "Requisiti di sistema",
    instPath: "/it/installation",
    instText: "Installazione",
    gcPath: "/it/gettingconnected",
    gcText: "Connettersi",
    wwsPath: "/it/workingwithsessions",
    wwsText: "Lavorare all'interno di una sessione",
    dashPath: "/it/dashboard",
    dashText: "Il cruscotto di gestione del cerchio",
    faqPath: "/it/faq",
    faqText: "Domande frequenti",
    planPath: "/it/plans",
    planText: "Piani e acquisti",
    clPath: "/it/changelog",
    clText: "Registro delle modifiche"
  },
  de: {
    homePath: "/de",
    homeText: "Willkommen",
    specsPath: "/de/systemspecs",
    specsText: "Systemanforderungen",
    instPath: "/de/installation",
    instText: "Einrichtung",
    gcPath: "/de/gettingconnected",
    gcText: "Verbunden werden",
    wwsPath: "/de/workingwithsessions",
    wwsText: "Arbeiten innerhalb einer Sitzung",
    dashPath: "/de/dashboard",
    dashText: "Das Rim Management Dashboard",
    faqPath: "/de/faq",
    faqText: "Häufig gestellte Fragen",
    planPath: "/de/plans",
    planText: "Planen und Kaufeng",
    clPath: "/de/changelog",
    clText: "Änderungsprotokoll"
  },
  sv: {
    homePath: "/sv",
    homeText: "Välkommen till",
    specsPath: "/sv/systemspecs",
    specsText: "Systemkrav",
    instPath: "/sv/installation",
    instText: "Installation",
    gcPath: "/sv/gettingconnected",
    gcText: "Att bli uppkopplad",
    wwsPath: "/sv/workingwithsessions",
    wwsText: "Arbeta inom en session",
    dashPath: "/sv/dashboard",
    dashText: "Instrumentpanelen för Rim Management",
    faqPath: "/sv/faq",
    faqText: "Vanliga frågor och svar",
    planPath: "/sv/plans",
    planText: "Planer och inköp",
    clPath: "/sv/changelog",
    clText: "Ändra logg"
  },
  pt: {
    homePath: "/pt",
    homeText: "Bem-vindo",
    specsPath: "/pt/systemspecs",
    specsText: "Requisitos do sistema",
    instPath: "/pt/installation",
    instText: "Instalação",
    gcPath: "/pt/gettingconnected",
    gcText: "Como se conectar",
    wwsPath: "/pt/workingwithsessions",
    wwsText: "Trabalhando em uma sessão",
    dashPath: "/pt/dashboard",
    dashText: "O painel de controle do Rim Management",
    faqPath: "/pt/faq",
    faqText: "Perguntas frequentes",
    planPath: "/pt/plans",
    planText: "Planos e compras",
    clPath: "/pt/changelog",
    clText: "Registro de alterações"
  },
};

export default languageMappings;
